### ISSUE TITLE
n future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.

### ISSUE THREAD

**Issue by welyt** [tompollard/tableone#139] opened 2023-02-28 07:58 UTC

**Comment by tompollard** [comment] 2023-04-20 18:35
Looks like a duplicate of https://github.com/tompollard/tableone/issues/140

**Closed by tompollard** 2023-04-20 18:35 UTC
